using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace cfGodotEngine.Binding
{
    [Generator(LanguageNames.CSharp)]
    public class BindingSourceGenerator : IIncrementalGenerator
    {
        private const string AttrMeta = "cfGodotEngine.Binding.BindingSourceAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var matched = context.SyntaxProvider.ForAttributeWithMetadataName(
                AttrMeta,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) =>
                {
                    var symbol = ctx.TargetSymbol as INamedTypeSymbol;
                    return symbol;
                });

            var grouped = matched.Collect();

            context.RegisterSourceOutput(grouped, (spc, classes) =>
            {
                if (classes.IsDefaultOrEmpty) return;

                foreach (var type in classes.Distinct(SymbolEqualityComparer.Default))
                {
                    var namedType = type as INamedTypeSymbol;
                    if (namedType == null) continue;

                    GenerateBindingPartial(spc, namedType);
                }
            });
        }

        private static void GenerateBindingPartial(SourceProductionContext spc, INamedTypeSymbol type)
        {
            var ns = type.ContainingNamespace.IsGlobalNamespace ? null : type.ContainingNamespace.ToDisplayString();
            var className = type.Name;
            var typeMods = GetTypeModifiers(type);

            var reactiveFields = new List<(IFieldSymbol field, string key)>();

            foreach (var member in type.GetMembers())
            {
                if (member is not IFieldSymbol field) continue;
                if (field.IsStatic) continue;
                if (!field.DeclaredAccessibility.HasFlag(Accessibility.Public)) continue;
                if (!field.IsReadOnly) continue;

                if (field.Type is not INamedTypeSymbol fieldType) continue;
                if (fieldType.OriginalDefinition == null) continue;
                if (fieldType.OriginalDefinition.Name != "ReactiveProperty") continue;
                if (fieldType.OriginalDefinition.ContainingNamespace?.ToDisplayString() != "cfEngine.Rx") continue;
                if (fieldType.TypeArguments.Length != 1) continue;

                reactiveFields.Add((field, field.Name));
            }

            if (reactiveFields.Count == 0)
            {
                var descriptor = new DiagnosticDescriptor(
                    id: "BIND002",
                    title: "[BindingSource] class has no ReactiveProperty fields",
                    messageFormat: "Class '{0}' is marked [BindingSource] but has no public readonly ReactiveProperty<T> fields",
                    category: "Binding",
                    DiagnosticSeverity.Warning,
                    isEnabledByDefault: true
                );
                spc.ReportDiagnostic(Diagnostic.Create(descriptor, type.Locations.FirstOrDefault(), className));
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            if (ns != null)
            {
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
            }

            sb.AppendLine($"{typeMods} {className} : global::cfGodotEngine.Binding.IBindingSource");
            sb.AppendLine("{");
            sb.AppendLine($"    private global::cfGodotEngine.Binding.PropertyMap _propertyMap;");
            sb.AppendLine();
            sb.AppendLine("    public global::cfGodotEngine.Binding.IPropertyMap GetBindings");
            sb.AppendLine("    {");
            sb.AppendLine("        get");
            sb.AppendLine("        {");
            sb.AppendLine("            if (_propertyMap == null)");
            sb.AppendLine("            {");
            sb.AppendLine("                _propertyMap = global::cfGodotEngine.Binding.PropertyMap.Build()");

            foreach (var (field, key) in reactiveFields)
            {
                var fieldType = (field.Type as INamedTypeSymbol)!;
                var typeArg = fieldType.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"                    .Add<{typeArg}>(nameof({key}), {key})");
            }

            sb.AppendLine("                    .Build();");
            sb.AppendLine("            }");
            sb.AppendLine("            return _propertyMap;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public global::System.IDisposable BeginUpdate()");
            sb.AppendLine("    {");
            sb.AppendLine("        if (_propertyMap == null) _ = GetBindings;");
            sb.AppendLine("        return _propertyMap.BeginUpdate();");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<string> GetBindingKeys()");
            sb.AppendLine("    {");
            sb.AppendLine("        return new string[]");
            sb.AppendLine("        {");

            foreach (var (_, key) in reactiveFields)
            {
                sb.AppendLine($"            nameof({key}),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource($"{className}.Binding.generated.cs", sb.ToString());
        }

        private static string GetTypeModifiers(INamedTypeSymbol t) =>
            t.TypeKind == TypeKind.Struct ? "public partial struct" : "public partial class";
    }
}
